src/ContainerRegistry/ImageContainerRegistry.swift
src/Main.swift

Fixes https://github.com/trycua/lume/issues/7

Display indicator at processing image layers

---

README.md

Document prebuilt images default password

---

docs/FAQ.md

Document how to install from a new macOS IPSW image

Update FAQ with custom IPSW

---

README.md
src/Commands/Set.swift
src/Errors/Errors.swift
src/FileSystem/VMConfig.swift
src/LumeController.swift
src/Server/Handlers.swift
src/Server/Requests.swift
src/VM/VM.swift
src/VM/VMDetails.swift
src/VM/VMDetailsPrinter.swift

Set display resolution

---

README.md
docs/API-Reference.md
src/Commands/Run.swift
src/LumeController.swift
src/Server/Handlers.swift
src/Server/Requests.swift
src/VM/VM.swift
src/Virtualization/VMVirtualizationService.swift
tests/Mocks/MockVM.swift
tests/VMTests.swift

This adds the option to start in recovery mode.
Fixes #36

Add recovery mode option

---

.all-contributorsrc
README.md

Addresses #40 
TODO:
Ref: https://allcontributors.org/docs/en/bot/installation
ping @pepicrft incase we're missing anything (?).

Add all contributors section

---

src/Commands/Serve.swift
src/Server/Server.swift

Serve port bound by another process

---

.github/workflows/publish-lume.yml
libs/lume/scripts/build/build-release-notarized.sh

Add support for ubi and mise installation methods.

Add support for ubi and mise

---

libs/lume/README.md
libs/lume/src/ContainerRegistry/ImageContainerRegistry.swift

This PR improves the disk image reassembly process to reduce both memory usage and storage requirements:
- Reduced storage requirements: Now reads directly from cached image parts instead of making temporary copies, reducing storage needs from 3x to just over 1x the image size
- Memory optimization: Implemented adaptive chunk sizing based on available system memory
- Reduced log noise: Limited progress reporting to 5% increments
- Enhanced stability: Added special handling for memory-constrained systems with more aggressive resource cleanup
These changes allow large images (60GB+) to be reassembled on systems with limited RAM and storage.

[Lume] Optimize disk image reassembly for performance and storage

---

notebooks/blog/build-your-own-operator-on-macos-1.ipynb

Add operator blogpost: https://www.trycua.com/blog/build-your-own-operator-on-macos-1

Add operator blogpost - part 1

---

libs/agent/agent/providers/openai/api_handler.py

Add reasoning summary by default: https://platform.openai.com/docs/guides/tools-computer-use?lang=javascript#1-send-a-request-to-the-model

[Agent] Add OpenAI generate summary

---

notebooks/gradio_agent_nb.ipynb

https://github.com/AK391/ai-gradio/pull/24

Add ai-gradio notebook

---

README.md

Update README with Gradio step.

Update README with gradio

---

libs/agent/agent/core/provider_config.py
libs/agent/agent/core/types.py
libs/agent/agent/providers/omni/clients/ollama.py
libs/agent/agent/providers/omni/loop.py
libs/agent/agent/providers/omni/types.py

Hi yall!
There is no developer guide for formatting incomming code in the Repo FYI.
This is the modified script that I am using locally to work with the toolkit. I wanted to add Ollama support further than the OpenAI interface due to the different API interfaces. All I did to verify was pip install -e . the agent directory, change the LLMProvider to OLLAMA in the agent notebook, and install the ollama pip package.
If y'all want to consider adding this, I can polish it with your feedback, if not no worries!

Add Ollama support in Omni parser

---

libs/agent/README.md

Fix leftover from previous Gradio docs

[Agent] Fix leftover Gradio docs

---

libs/lume/src/ContainerRegistry/ImageContainerRegistry.swift

- **Space efficiency**: Implemented sparse file technique that minimizes disk usage during image assembly
- **Download optimization**: Enhanced download engine with adaptive concurrency and network optimizations
- **Progress metrics**: Added real-time speed statistics with ETA and download summary
- Reduces disk space requirements by ~50%
- Improves download speeds through parallelism and connection tuning
- Provides better user feedback during large image downloads

[Lume] Optimize VM image assembly

---

libs/agent/agent/core/base.py
libs/agent/agent/core/callbacks.py
libs/agent/agent/providers/omni/clients/oaicompat.py
libs/agent/agent/providers/omni/loop.py
libs/agent/agent/providers/openai/loop.py
libs/agent/agent/ui/gradio/app.py
libs/som/som/ocr.py

- Added richer chat metadata (screenshots, tool calls)
- Added asynchronous streaming of messages
- Added UI options for custom OpenAI-compatible URLs and API keys
- Fixed event loop issues in multi-turn conversations
- Fixed agent loop error when updating configuration

[Agent] Improved Gradio UI

---

libs/mcp-server/scripts/install_mcp_server.sh

this improves logging when the installation fails

Update install_mcp_server.sh - remove piping to /dev/null

---

README.md
examples/computer_ui_examples.py
libs/agent/agent/providers/openai/tools/computer.py
libs/computer-server/computer_server/handlers/macos.py
libs/computer/README.md
libs/computer/computer/interface/macos.py
libs/computer/computer/ui/__init__.py
libs/computer/computer/ui/gradio/__init__.py
libs/computer/computer/ui/gradio/app.py
libs/computer/pyproject.toml

- Add Gradio UI for computer module to create and share datasets for computer-use benchmarks, demonstrations, etc
- Fix double-click tool in computer-server
- Fix scroll behavior to use scroll wheel instead of pgup/pgdown, and adjusted OpenAI's CUA scroll intensity
- Fix hotkey mapping to more robustly handle key combinations
- Add README documentation with demonstration video
This PR extends the computer module with a Gradio-based UI similar to the agent UI, making it easier to create data for training and benchmarking.

[Computer] Add Gradio UI and fix interaction bugs

---

libs/computer/README.md

docs: update computer/README.md

---

libs/mcp-server/README.md

[Docs] Add MCP pre-requisites

---

libs/agent/agent/providers/omni/clients/oaicompat.py
libs/agent/agent/providers/uitars/clients/oaicompat.py
libs/agent/agent/providers/uitars/loop.py

Fixes "'str' object has no attribute 'get'" error from UI-TARS API by adding proper handling for text messages with box coordinates.

[Agent] Fixes the UITarsLoop error `'str' object has no attribute 'get'

---

libs/agent/agent/providers/anthropic/tools/computer.py
libs/agent/agent/providers/openai/tools/computer.py
libs/agent/agent/providers/uitars/clients/oaicompat.py
libs/agent/agent/providers/uitars/loop.py
libs/agent/agent/providers/uitars/utils.py
libs/agent/agent/ui/gradio/app.py
libs/computer-server/computer_server/handlers/base.py
libs/computer-server/computer_server/handlers/macos.py
libs/computer-server/computer_server/main.py
libs/computer/computer/interface/base.py
libs/computer/computer/interface/macos.py

This PR standardizes the UITARS loop responses to use the AgentResponse format. The Gradio UI now displays AgentResponse objects more clearly to reflect the standardized output.
Also includes some bugfixes for the drag tool, and allows for dragging along a path with more than two points to support upcoming agent features

[Agent] Improved drag tool and standardized UITARS response

---

libs/mcp-server/README.md
libs/mcp-server/mcp_server/server.py
libs/mcp-server/scripts/start_mcp_server.sh

Fixed:
- Fixed agent trajectories sometimes missing the text & reasoning in the tool call results
Added:
- `screenshot_cua` tool so an MCP agent can observe the VM state before executing tasks
- UITARS loop to MCP server
- Screenshots in MCP tool call results
- MCP Development guide in `mcp-server/README.md`

[Agent] MCP Improvements (UITARS and image support)

---

libs/lume/src/Virtualization/VMVirtualizationService.swift

Add clipboard and audio device

Add clipboard and audio device

---

libs/computer-server/computer_server/handlers/linux.py
libs/computer/computer/computer.py
libs/computer/computer/ui/gradio/app.py

This PR fixes some bugs experienced during initialization and usage of a Ubuntu VM.
**Changes:** 
- Changed `computer.run()` to skip calling `run_vm` if the `get_vm` status is `running`
- Added additional assert to make sure `ephemeral` and `storage` aren't both set
- Fixed an error that occured with the hotkey command due to an incorrect kwarg
- Added a linux preset to the computer UI (Temporarily disabled the switch for now, as it requires manual setup of the cua-computer-server)

[Computer] Fix hotkeys and computer initialization

---

README.md

Refactored the Quick Start section to guide users through the managed installation .sh on Windows/Linux, along with the option to manually run the commands yourself.

Rewording README for Windows/Linux

---

docs/src/app/layout.tsx

This PR fixes the search issues with the documentation website.

[Docs] Fix Search
