src/Commands/Pull.swift
src/Commands/Run.swift
src/LumeController.swift

Normalize VM name

---

src/Commands/Get.swift
src/Commands/List.swift
src/Commands/Options/FormatOption.swift
src/VM/VMDetailsPrinter.swift
tests/VM/VMDetailsPrinterTests.swift

I'm adding support for a `--json` flag to the `lume get` and `lume list` command. When interfacing with `lume` programmatically, having the responses as a decodable JSON is useful.

Add `--json` support to get and list

---

.github/workflows/lume.yml

I noticed there are no CI pipelines in this repository, which can cause some regressions to be introduced in PRs. 
This PR adds a GitHub action with two job, one that runs the tests, and another one that builds the package for the release configuration.

Add CI pipelines to test and build the code on every branch commit and pull request

---

tests/VM/VMDetailsPrinterTests.swift

The test in `tests/VM/VMDetailsPrinterTests.swift` was broken.
```swift
Building for debugging...
[4/4] Write swift-version--58304C5D6DBC2206.txt
Build complete! (0.17s)
Building for debugging...
/Users/aktech/dev/lume/tests/VM/VMDetailsPrinterTests.swift:13:87: error: missing argument for parameter 'display' in call
11 |                                              cpuCount: 2,
12 |                                              memorySize: 1024,
13 |                                              diskSize: .init(allocated: 24, total: 30),
|                                                                                       `- error: missing argument for parameter 'display' in call
14 |                                              status: "status",
15 | …
```

Fix broken test: `VMDetailsPrinterTests`

---

libs/lume/docs/API-Reference.md

Looks like the url was incorrect in the API docs.
```bash
curl --connect-timeout 6000 \
--max-time 5000 \
-X POST \
-H "Content-Type: application/json" \
-d '{
"name": "macos-sequoia-vanilla_latest",
"newName": "cloned-vm"
}' \
http://localhost:3000/lume/vms/macos-sequoia-vanilla_latest/clone
Not found%
```
```bash
curl --connect-timeout 6000 \
--max-time 5000 \
-X POST \
-H "Content-Type: application/json" \
-d '{
"name": "macos-sequoia-vanilla_latest",
"newName": "cloned-vm"
}' \
http://localhost:3000/lume/vms/clone
{"message":"VM cloned successfully","source":"macos-sequoia-vanilla_latest","destination":"cloned-vm"}%
```
TODO for later: It would great to add auto-generated docs via something like swagger.

Fix url for clone endpoint

---

libs/lume/docs/API-Reference.md
libs/lume/src/Commands/Pull.swift
libs/lume/src/ContainerRegistry/ImageContainerRegistry.swift
libs/lume/src/LumeController.swift
libs/lume/src/Server/Handlers.swift
libs/lume/src/Server/Requests.swift

Add `--no-cache` option in lume pull

---

libs/lume/src/ContainerRegistry/ImageContainerRegistry.swift
libs/lume/src/Errors/Errors.swift

Fix an issue on <16GB macOS where the reassemble process is killed by the system due to memory constraints using swift.

[Lume] Fix reassemble kill

---

docs/FAQ.md

This PR enhances the `docs/FAQ.md` by adding detailed troubleshooting sections for two common and potentially blocking issues encountered when setting up and running the CUA framework, particularly for new users.
**1. EasyOCR `[SSL: CERTIFICATE_VERIFY_FAILED]` Errors**
*   **Problem:** Users frequently encounter SSL certificate verification errors when EasyOCR attempts its initial model download, preventing OCR capabilities.
*   **Solution Added:** A new FAQ entry details the cause (Python SSL context missing CA certificates) and provides the standard fix: setting the `SSL_CERT_FILE` and `REQUESTS_CA_BUNDLE` environment variables using the `certifi` package.
**2. Lume VM Startup / IP Address Failures**
*   **Problem:** The agent often hangs during VM startup, failing to get an IP address …

Docs: Add EasyOCR SSL & Lume VM Startup Troubleshooting to FAQ

---

libs/lume/src/LumeController.swift

- Ran lume clone image_name new_image_name to clone an existing image.
- After running the original image with lume run image_name,
- The cloned image (new_image_name) also appeared as running in the output of lume ls.
- The original and cloned images should run independently.
- Starting the original image should not cause the cloned image to start or appear active.
- Updated the cloning logic to generate a new identifier to ensure separation between the instances.

Update Mac identifier during clone process

---

README.md
libs/lume/scripts/install.sh
notebooks/computer_nb.ipynb

Fix: Make installation script sudo-free by default (#132)
Changes the default installation directory to ~/.local/bin instead of /usr/local/bin to avoid needing sudo. Adds CLI options with --install-dir parameter for custom locations and improves permission checking with helpful messages. Users can still install to system directories if they choose, but the default is now secure and user-friendly.

[Lume] Update lume install location

---

libs/agent/agent/providers/openai/tools/computer.py
libs/agent/agent/providers/uitars/clients/oaicompat.py
libs/agent/agent/providers/uitars/loop.py
libs/agent/agent/providers/uitars/prompts.py
libs/agent/agent/providers/uitars/tools/computer.py
libs/computer/computer/interface/models.py

- Fixed OpenAI loop and UITARS loop not using `computer.interface.hotkey`
- Reduced scrolling sensitivity for OpenAI's loop by a factor of 2.5x
- Added `top_p` parameter to UITARS inference (using the value from the UITARS repo)
- Added additional prompt for UITARS to use mac hotkeys: `(You are operating on macOS, use 'cmd' instead of 'ctrl' for most shortcuts e.g., hotkey(key='cmd c') for copy, hotkey(key='cmd v') for paste, hotkey(key='cmd t') for new tab).)`
- Added key mappings for modifier keys (e.g., 'command', '⌘', 'super', '⌥', etc)

[Agent] Fixes for hotkeys, scrolling sensitivity

---

libs/computer/computer/computer.py

see: https://github.com/trycua/cua/issues/124
renames initialization argument `os` to `os_type` to avoid collision with module
> 
> This section in the Computer.__init__ method:
> 
>  if shared_directories:
>     for path in shared_directories:
>         abs_path = os.path.abspath(os.path.expanduser(path))  # type: ignore[attr-defined]
>         if not os.path.exists(abs_path):  # type: ignore[attr-defined]
>             raise ValueError(f"Shared directory does not exist: {path}")
>         self.shared_paths.append(abs_path)
> 
> fails with:
> 
> abs_path = os.path.abspath(os.path.expanduser(path))  # type: ignore[attr-defined]
>                ^^^^^^^
> AttributeError: 'str' object has no attribute 'path'
> 
> because the module name is being shadowed by the init variable os, which is a …

[Computer] Renames os arg to os_type to avoid module collision

---

libs/lume/src/FileSystem/Home.swift

This PR fixes a bug when trying to clone a VM from a direct path (e.g trying to clone from a lumier location into a typical lume configured storage location).
Before
After

Add support for direct path when cloning VM

---

libs/computer/computer/providers/lumier/provider.py

This lets arbitrary lume os images be used with the lumier `computer` provider

Lumier computer provider takes non-trycua image

---

pyproject.toml

Certain dependencies such as HUD also have this restriction, so this is necessary for those dependencies to work.

Restrict root project to Python versions below 3.14

---

README.md

Unified capitalization of 'Get started' in the Quick Start section of the README.

docs: unifiy capitalization in README

---

docs/content/docs/libraries/lumier/building-lumier.mdx
docs/content/docs/libraries/lumier/docker-compose.mdx
docs/content/docs/libraries/lumier/docker.mdx
docs/content/docs/libraries/lumier/index.mdx
docs/content/docs/libraries/lumier/installation.mdx
docs/content/docs/libraries/lumier/meta.json
libs/lumier/README.md

This PR moves documentation from the Lumier README to the official documentation.
**README:**
* Removed installation details about Lume service port
* Removed "How It Works" explanation
* Removed detailed usage guides (saving VM state, file sharing, automation, Docker Compose, building/customizing Lumier, configuration options)
* Added a short note linking to official docs for persistence setup
* Added a "Docs" section with links to Installation, Docker, Docker Compose, and Building Lumier pages
**Official documentation:**
* Added new pages: `installation.mdx`, `docker.mdx`, `docker-compose.mdx`, `building-lumier.mdx`
* Split and reorganized README content into those pages
* Improved structure with sections for Installation, Docker usage, Compose setup, building/customizing Lumier
* Added …

Move Lumier README to docs

---

examples/evals/hud_eval_examples.py

This PR updates the hud_eval_examples.py script to make running HUD evaluations simpler and more robust:
Path-agnostic .env discovery: replaced hardcoded .env path with find_dotenv, allowing the script to automatically locate the nearest .env in the repo hierarchy.
Environment validation: script now raises a clear error if HUD_API_KEY is missing instead of failing silently.
Minimal HUD eval flow: removed Docker/local setup references—script focuses only on running HUD evaluations with run_full_dataset.
Improved UX: users can place .env at the repo root (or export vars in their shell) and run the example from any directory without manual copying.
This change reduces setup friction and ensures consistent results across different environments.

🔧 Improve HUD eval script: auto-discover .env and simplify usage

---

libs/lume/src/Server/Server.swift

Signed-off-by: Jagjeevan Kashid <jagjeevandev97@gmail.com>
I have updated server end point as suggested by @jamesmurdza in issue #372

fix: updated server endpoint from `/vms/push` to `/lume/vms/push`

---

README.md
docs/content/docs/agent-sdk/supported-agents/computer-use-agents.mdx
docs/content/docs/quickstart-cli.mdx

This PR mentions support for the newly released Claude Sonnet 4.5 in the docs. No changes were needed in the Agent SDK to enable support.

Add Sonnet 4.5 support to docs
